# Generated by Django 2.1 on 2019-02-11 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190210_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 11, 2, 18, 52, 914148), verbose_name='date published'),
        ),
    ]
