# Generated by Django 2.1 on 2019-02-16 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190216_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 16, 5, 32, 10, 115536), verbose_name='date published'),
        ),
    ]
